# Brazilian E-Commerce Sales and Customer Analysis

### Exploring Sales, Customers, Products, Sellers, Payments, Delivery and Reviews
*Tools Used:* Python, Pandas, NumPy, Matplotlib and Seaborn

*Dataset Source:* Olist Brazilian E-Commerce Public Dataset

## 1. Project Overview

This project analyses the Brazilian E-Commerce Public Dataset provided by Olist.

The dataset contains information related to orders, customers, products, sellers, payments, reviews and delivery. The data is distributed across multiple related CSV files.

The objective of this project is to clean, transform and integrate these datasets and perform Exploratory Data Analysis (EDA) to identify meaningful patterns in e-commerce sales and customer behaviour.

The analysis focuses on sales performance, product categories, customer locations, payment methods, seller activity, delivery performance and customer satisfaction.

## 2. Problem Statement

The Olist e-commerce dataset contains information spread across multiple tables, making it difficult to directly analyse the overall business performance.

The purpose of this project is to integrate the related datasets, perform data cleaning and preprocessing, and analyse the resulting data to answer important business questions.

### Key Questions

1. How did sales change over time?
2. Which product categories generated the highest sales?
3. Which Brazilian states contributed the most orders?
4. What payment methods were most commonly used?
5. How were customer review scores distributed?
6. How long did customers wait for their orders?
7. Is delivery performance related to customer satisfaction?
8. Which sellers and product categories contributed significantly to sales?

## 3. Dataset Description

The Olist dataset contains 9 CSV files:

| Dataset | Description |
|---|---|
| olist_orders_dataset | Order status and order timestamps |
| olist_order_items_dataset | Products, sellers, prices and freight |
| olist_customers_dataset | Customer information and location |
| olist_products_dataset | Product attributes |
| olist_sellers_dataset | Seller information and location |
| olist_order_payments_dataset | Payment information |
| olist_order_reviews_dataset | Customer review information |
| product_category_name_translation | Portuguese to English product category translation |
| olist_geolocation_dataset | Brazilian ZIP-code geographic information |

The tables are related through identifiers such as order_id, customer_id, product_id and seller_id.

## 4. Import Required Libraries

The following Python libraries are used for data manipulation, numerical operations, data visualization and statistical exploration

In [3]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

sns.set_style("whitegrid")

## 5. Loading the Datasets

The original Olist dataset contains multiple CSV files. Each file represents a different business entity or transaction-related information.

The datasets are loaded separately first. This allows us to inspect the structure and quality of each table before merging them

In [4]:
orders = pd.read_csv("olist_orders_dataset.csv")

customers = pd.read_csv("olist_customers_dataset.csv")

order_items = pd.read_csv("olist_order_items_dataset.csv")

products = pd.read_csv("olist_products_dataset.csv")

sellers = pd.read_csv("olist_sellers_dataset.csv")

payments = pd.read_csv("olist_order_payments_dataset.csv")

reviews = pd.read_csv("olist_order_reviews_dataset.csv")

translation = pd.read_csv("product_category_name_translation.csv")

geolocation = pd.read_csv("olist_geolocation_dataset.csv")
print("All datasets loaded successfully!")

All datasets loaded successfully!

In [5]:
datasets = {
    "Orders": orders,
    "Customers": customers,
    "Order Items": order_items,
    "Products": products,
    "Sellers": sellers,
    "Payments": payments,
    "Reviews": reviews,
    "Translation": translation,
    "Geolocation": geolocation
}

print("Dataset dictionary created successfully!")

Dataset dictionary created successfully!

# INITIAL DATA EXPLORATION

## 6. Checking Dataset Dimensions

The shape of each dataset is checked to determine the number of rows and columns present in the individual tables.

This is useful for understanding the size of the data before performing cleaning and merging operations

In [6]:
print("Orders:", orders.shape)
print("Customers:", customers.shape)
print("Order Items:", order_items.shape)
print("Products:", products.shape)
print("Sellers:", sellers.shape)
print("Payments:", payments.shape)
print("Reviews:", reviews.shape)
print("Translation:", translation.shape)
print("Geolocation:", geolocation.shape)

Orders: (99441, 8)
Customers: (99441, 5)
Order Items: (112650, 7)
Products: (32951, 9)
Sellers: (3095, 4)
Payments: (103886, 5)
Reviews: (99224, 7)
Translation: (71, 2)
Geolocation: (1000163, 5)

### Observation

The datasets contain different numbers of rows and columns because each table represents a different entity or transaction level.

For example, one order can contain multiple order items, and an order can also have multiple payment records. Therefore, the number of records differs between tables.

## View First Five Records

## 7. Previewing the Datasets

The first five records of the main datasets are displayed to understand their columns and the type of information stored in each table.

In [7]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [8]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [9]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [10]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [11]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

## 8. Checking Dataset Information

The `info()` function is used to examine column names, data types and the number of non-null values.

This helps identify columns that require data type conversion, especially date and timestamp columns.

In [12]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [13]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [14]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [15]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

## 9. Checking Missing Values

Missing values can affect calculations and visualizations. Therefore, missing values are identified before performing data transformation and analysis.

In [16]:
datasets = {
    "Orders": orders,
    "Customers": customers,
    "Order Items": order_items,
    "Products": products,
    "Sellers": sellers,
    "Payments": payments,
    "Reviews": reviews,
    "Translation": translation,
    "Geolocation": geolocation
}

for name, df in datasets.items():
    print("\n", name)
    print(df.isnull().sum())

 Orders
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

 Customers
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

 Order Items
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

 Products
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

 Sellers
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

 Payments
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

 Reviews
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

 Translation
product_category_name            0
product_category_name_english    0
dtype: int64

 Geolocation
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

### Observation

The missing-value results will be examined column by column. Missing values are not automatically replaced with zero because the appropriate treatment depends on the meaning and data type of each column.

## 10. Checking Duplicate Records

Duplicate records are checked because duplicated observations can affect statistical calculations and sales analysis.

In [17]:
for name, df in datasets.items():
    print(name, ":", df.duplicated().sum(), "duplicate rows")

Orders : 0 duplicate rows
Customers : 0 duplicate rows
Order Items : 0 duplicate rows
Products : 0 duplicate rows
Sellers : 0 duplicate rows
Payments : 0 duplicate rows
Reviews : 0 duplicate rows
Translation : 0 duplicate rows
Geolocation : 261831 duplicate rows

### Observation

The duplicate counts are reviewed for each dataset. Duplicate handling will be performed only where appropriate, because repeated records can sometimes represent legitimate transactions rather than accidental duplicates.

# DATA CLEANING

## 11. Converting Date and Time Columns

Several columns in the orders dataset contain dates and timestamps stored as text.

These columns are converted into datetime format so that delivery duration, monthly trends and yearly trends can be calculated accurately.

In [18]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col], errors="coerce")

In [19]:
orders[date_columns].dtypes

order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

### Check missing values in important order dates

In [20]:
orders[date_columns].isnull().sum()

order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

### Observation

Some order timestamps may contain missing values because not every order reached every stage of the delivery process. For example, cancelled or unavailable orders may not have a customer delivery date.

These missing dates will not be replaced with artificial dates because doing so could create incorrect delivery-duration calculations.

# MERGING THE TABLES

# 12. Data Integration and Table Merging

The Olist dataset is divided into multiple related tables.

To perform combined analysis, the relevant tables need to be integrated using common key columns.

The main relationships are:

- `orders` → `customers` using `customer_id`
- `orders` → `order_items` using `order_id`
- `order_items` → `products` using `product_id`
- `order_items` → `sellers` using `seller_id`
- `orders` → `payments` using `order_id`
- `orders` → `reviews` using `order_id`
- `products` → `translation` using `product_category_name`

A LEFT JOIN is used so that all records from the main/base dataset are retained while matching information from the related table is added.

## 13. Creating the Base Dataset

The `orders` table is selected as the starting point because `order_id` is the central identifier connecting order information with customers, items, payments and reviews.

A copy is created so that the original dataset remains unchanged.

In [21]:
master_df = orders.copy()

master_df.shape

(99441, 8)

## 14. Merging Orders with Customer Information

The orders and customers tables are connected through `customer_id`.

A LEFT JOIN is performed using `customer_id`.

The orders table is kept as the left table so that all orders are retained while customer information is added where a matching customer record exists.

In [22]:
master_df = master_df.merge(
    customers,
    on="customer_id",
    how="left"
)

In [23]:
master_df.shape

(99441, 12)

In [24]:
master_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

### Observation

Customer location and customer identification information has now been added to the order-level dataset.

The LEFT JOIN preserves the records from the orders table.

## 15. Merging Order Items

The order items table contains information about individual products purchased within an order.

The common key between the two datasets is `order_id`.

A LEFT JOIN is used to add order-item information to the master dataset.

An important point is that one order can contain multiple items. Therefore, the number of rows can increase after this merge. This is expected because the resulting dataset is now at the order-item level.

In [25]:
master_df = master_df.merge(
    order_items,
    on="order_id",
    how="left"
)

In [26]:
master_df.shape

(113425, 18)

In [27]:
master_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,1.0,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,1.0,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72

### Observation

The number of rows increased after merging because an individual order may contain multiple products.

The resulting master dataset represents individual order items while retaining the order and customer information.

## 16. Merging Product Information

The order items table contains `product_id`, which can be used to connect each order item with the corresponding product information.

A LEFT JOIN is performed using `product_id`.

In [28]:
master_df = master_df.merge(
    products,
    on="product_id",
    how="left"
)

In [29]:
master_df.shape

(113425, 26)

## 17. Merging Seller Information

Each order item is associated with a seller through `seller_id`.

Seller information such as seller city, state and ZIP code is added using a LEFT JOIN.

In [30]:
master_df = master_df.merge(
    sellers,
    on="seller_id",
    how="left"
)

In [31]:
master_df.shape

(113425, 29)

## 18. Merging Product Category Translation

The original product category names are provided in Portuguese.

The translation table contains the English equivalent of the category names.

The two tables are connected through `product_category_name`.

In [32]:
master_df = master_df.merge(
    translation,
    on="product_category_name",
    how="left"
)

In [33]:
master_df = master_df.merge(
    translation,
    on="product_category_name",
    how="left"
)

## 19. Preparing Payment Data Before Merging

The payment table can contain multiple records for the same order.

Directly merging the raw payment table with the order-item-level master dataset could create unnecessary row multiplication.

Therefore, the payment data is aggregated at the order level before performing the LEFT JOIN.

The total payment value is calculated by summing payment values for each order.

In [34]:
payment_summary = (
    payments
    .groupby("order_id")
    .agg(
        total_payment_value=("payment_value", "sum"),
        payment_count=("payment_type", "count"),
        max_installments=("payment_installments", "max")
    )
    .reset_index()
)

In [35]:
payment_summary.head()

,order_id,total_payment_value,payment_count,max_installments
0,00010242fe8c5a6d1ba2dd792cb16214,72.19,1,2
1,00018f77f2f0320c557190d7a144bdd3,259.83,1,3
2,000229ec398224ef6ca0657da4fc703e,216.87,1,5
3,00024acbcdf0a6daa1e931b038114c75,25.78,1,2
4,00042b26cf59d7ce69dfabb4e55b4fd9,218.04,1,3

### merge

In [36]:
master_df = master_df.merge(
    payment_summary,
    on="order_id",
    how="left"
)

## 20. Preparing Review Data Before Merging

The review table can contain more than one record associated with an order.

To avoid unnecessary row multiplication, the review information is summarized at the order level before merging.

The average review score is calculated for each order.

In [37]:
review_summary = (
    reviews
    .groupby("order_id")
    .agg(
        average_review_score=("review_score", "mean"),
        review_count=("review_score", "count")
    )
    .reset_index()
)

In [38]:
review_summary.head()

                           order_id  average_review_score  review_count
0  00010242fe8c5a6d1ba2dd792cb16214                   5.0             1
1  00018f77f2f0320c557190d7a144bdd3                   4.0             1
2  000229ec398224ef6ca0657da4fc703e                   5.0             1
3  00024acbcdf0a6daa1e931b038114c75                   4.0             1
4  00042b26cf59d7ce69dfabb4e55b4fd9                   5.0             1

### merge

In [39]:
master_df = master_df.merge(
    review_summary,
    on="order_id",
    how="left"
)

## 21. Preparing Geolocation Data

The geolocation dataset may contain multiple latitude and longitude records for the same ZIP-code prefix.

Therefore, the data is aggregated by ZIP-code prefix before merging.

The mean latitude and longitude are used as representative coordinates for each ZIP-code prefix.

In [40]:
geo_summary = (
    geolocation
    .groupby("geolocation_zip_code_prefix")
    .agg(
        latitude=("geolocation_lat", "mean"),
        longitude=("geolocation_lng", "mean")
    )
    .reset_index()
)

In [41]:
# Now customer location:
customer_geo = geo_summary.rename(
    columns={
        "geolocation_zip_code_prefix": "customer_zip_code_prefix",
        "latitude": "customer_latitude",
        "longitude": "customer_longitude"
    }
)

In [42]:
# merge
master_df = master_df.merge(
    customer_geo,
    on="customer_zip_code_prefix",
    how="left"
)

In [43]:
seller_geo = geo_summary.rename(
    columns={
        "geolocation_zip_code_prefix": "seller_zip_code_prefix",
        "latitude": "seller_latitude",
        "longitude": "seller_longitude"
    }
)

In [44]:
master_df = master_df.merge(
    seller_geo,
    on="seller_zip_code_prefix",
    how="left"
)

### Observation

The geolocation information has been aggregated before merging to avoid unnecessary duplication of order-item records.

The resulting master dataset now contains customer and seller geographic information where matching ZIP-code information is available.

## 22. Final Master Dataset

After completing the required LEFT JOIN operations, the resulting master dataset combines information from the major Olist tables.

The final dataset can now be used for feature engineering and exploratory data analysis.

In [45]:
master_df.shape

(113425, 40)

In [46]:
master_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_category_name_english_y,total_payment_value,payment_count,max_installments,average_review_score,review_count,customer_latitude,customer_longitude,seller_latitude,seller_longitude
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,housewares,38.71,3.0,1.0,4.0,1.0,-23.576983,-46.587161,-23.680729,-46.444238
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,perfumery,141.46,1.0,1.0,4.0,1.0,-12.177924,-44.660711,-19.807681,-43.980427
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,auto,179.12,1.0,3.0,5.0,1.0,-16.745150,-48.514783,-21.363502,-48.229601
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,...,pet_shop,72.20,1.0,1.0,5.0,1.0,-5.774190,-35.271143,-19.837682,-43.924053
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,stationery,28.62,1.0,1.0,5.0,1.0,-23.676370,-46.514627,-23.543395,-46.262086

In [47]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113425 entries, 0 to 113424
Data columns (total 40 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   order_id                         113425 non-null  object
 1   customer_id                      113425 non-null  object
 2   order_status                     113425 non-null  object
 3   order_purchase_timestamp         113425 non-null  datetime64[ns]
 4   order_approved_at                113264 non-null  datetime64[ns]
 5   order_delivered_carrier_date     111457 non-null  datetime64[ns]
 6   order_delivered_customer_date    110196 non-null  datetime64[ns]
 7   order_estimated_delivery_date    113425 non-null  datetime64[ns]
 8   customer_unique_id               113425 non-null  object
 9   customer_zip_code_prefix         113425 non-null  int64
 10  customer_city                    113425 non-null  object
 11  customer_state                   113425 non-null  object
 12  order_item_id                    112650 non-null  float64
 13  product_id                       112650 non-null  object
 14  seller_id                        112650 non-null  object
 15  shipping_limit_date              112650 non-null  object
 16  price                            112650 non-null  float64
 17  freight_value                    112650 non-null  float64
 18  product_category_name            111047 non-null  object
 19  product_name_lenght              111047 non-null  float64
 20  product_description_lenght       111047 non-null  float64
 21  product_photos_qty               111047 non-null  float64
 22  product_weight_g                 112632 non-null  float64
 23  product_length_cm                112632 non-null  float64
 24  product_height_cm                112632 non-null  float64
 25  product_width_cm                 112632 non-null  float64
 26  seller_zip_code_prefix           112650 non-null  float64
 27  seller_city                      112650 non-null  object
 28  seller_state                     112650 non-null  object
 29  product_category_name_english_x  111023 non-null  object
 30  product_category_name_english_y  111023 non-null  object
 31  total_payment_value              113422 non-null  float64
 32  payment_count                    113422 non-null  float64
 33  max_installments                 113422 non-null  float64
 34  average_review_score             112464 non-null  float64
 35  review_count                     112464 non-null  float64
 36  customer_latitude                113119 non-null  float64
 37  customer_longitude               113119 non-null  float64
 38  seller_latitude                  112397 non-null  float64
 39  seller_longitude                 112397 non-null  float64
dtypes: datetime64[ns](5), float64(20), int64(1), object(14)
memory usage: 34.6+ MB

## 23. Creating Derived Features

Derived features are created from existing columns to support deeper analysis.

For the order-item-level dataset, item revenue is calculated as product price plus freight value.

In [48]:
master_df["item_revenue"] = (
    master_df["price"] + master_df["freight_value"]
)

## 25. Extract Year, Month and Day

In [49]:

master_df["purchase_year"] = (
    master_df["order_purchase_timestamp"].dt.year
)

master_df["purchase_month"] = (
    master_df["order_purchase_timestamp"].dt.month
)

master_df["purchase_month_name"] = (
    master_df["order_purchase_timestamp"].dt.strftime("%B")
)

master_df["purchase_day"] = (
    master_df["order_purchase_timestamp"].dt.day
)

## 24. Calculating Delivery Duration

Delivery duration is calculated as the number of days between the purchase timestamp and the date on which the customer received the order.

Orders without a customer delivery date will result in missing delivery duration values because the order did not have a completed delivery record.

In [50]:
master_df["delivery_days"] = (
    master_df["order_delivered_customer_date"]
    - master_df["order_purchase_timestamp"]
).dt.days

## 25. Calculating Delivery Delay

Delivery delay is calculated by comparing the actual customer delivery date with the estimated delivery date.

A positive value indicates delivery after the estimated date, while a negative value indicates delivery before the estimated date.

In [51]:
master_df["delivery_delay_days"] = (
    master_df["order_delivered_customer_date"]
    - master_df["order_estimated_delivery_date"]
).dt.days

## 28. Create Purchase Month-Year

In [52]:

master_df["purchase_month_year"] = (
    master_df["order_purchase_timestamp"]
    .dt.to_period("M")
    .astype(str)
)